export const UI_TEXT = {
  nav: {
    home: "Home",
    friends: "Friends",
    upload: "Upload",
    inbox: "Inbox",
    profile: "Profile",
  },
  header: {
    live: "Live",
    following: "Following",
    forYou: "For You",
    search: "Search",
  },
  placeholder: {
    title: "Page not built yet",
    description: "This screen will be implemented in a future update.",
  },
  upload: {
    title: "Upload video",
    subtitle: "Create a new post using mock upload flow",
    mockNotice:
      "Privacy notice: this demo stores uploads locally in your browser only. Data is not sent to external servers.",
    caption: "Caption",
    descriptionPlaceholder: "Describe your video",
    submit: "Publish",
    publishing: "Publishing...",
    uploadedSuccess: "File uploaded successfully",
    readyToPublish: "Ready to publish",
    selectedFile: "Selected file",
    uploading: "Uploading file...",
    unsupportedFile: "Unsupported file",
    dropToUpload: "Drop file to upload",
    selectVideo: "Select a video to upload",
    dragAndDrop: "Or drag and drop your file",
    formatRequirement: "MP4 or WebM",
    resolutionRequirement: "At least 720x1280 resolution",
    durationRequirement: "Up to 180 seconds",
    cloudIconAlt: "Upload cloud icon",
    publishSuccess: "Video published successfully",
  },
  video: {
    play: "Play video",
    pause: "Pause video",
    followUser: "Follow user",
    albumCover: "Album cover",
    likes: "likes",
    comments: "comments",
    bookmarks: "bookmarks",
    shares: "shares",
    pendingFeature: "Feature in progress",
    shareMenuTitle: "Share to",
    copyLink: "Copy link",
    systemShare: "System share",
    sendToFriend: "Send to a friend",
    repost: "Repost",
    cancel: "Cancel",
    linkCopied: "Video link copied",
    commentsTitle: "Comments",
    commentsPlaceholder: "Add a comment...",
    postComment: "Post",
    close: "Close",
    follow: "Follow",
    following: "Following",
  },
  friendsPage: {
    title: "Friends",
    subtitle: "Suggested creators for you",
    connectButton: "Connect",
    mutualFollowers: "mutual followers",
    activityTitle: "Recent activity",
    followedYou: "followed you",
    likedPost: "liked your post",
    sentInvite: "sent you an invite",
  },
  inboxPage: {
    title: "Inbox",
    filters: {
      all: "All activity",
      mentions: "Mentions",
      comments: "Comments",
    },
    markRead: "Mark all as read",
    now: "now",
  },
  profilePage: {
    editProfile: "Edit profile",
    following: "Following",
    followers: "Followers",
    likes: "Likes",
    bioTitle: "Bio",
    analytics: "Analytics",
    profileViews: "Profile views",
    postViews: "Post views",
    likesThisWeek: "Likes this week",
    contentGrid: "Recent videos",
  },
  mockDisclaimer:
    "Demo notice: all data shown on this screen is mock data for preview purposes only.",
};
